### ISSUE TITLE
Moi!

### ISSUE THREAD

**Issue by EetuPajamaki** [randomusert/fpp#3]
Älä varasta minun koodia saatana
![image](https://github.com/randomusert/fpp/assets/157633543/c10356aa-454b-4214-8c4b-475569681bfc)
![image](https://github.com/randomusert/fpp/assets/157633543/81a255cc-b24e-4b41-89a4-8f31806b366d)

**Comment by EetuPajamaki** [comment]
![image](https://github.com/randomusert/fpp/assets/157633543/b96db58f-7a7c-46a0-acbe-ff6697a87b87)

**Comment by randomusert** [comment]
what???????????????????????????
